//USER REGISTRATION
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

//USER LOGIN
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

//USER LOGOUT
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

//USER PROFILE
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

//USER UPDATE
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

// LIST USERS
export const LIST_USERS_REQUEST = "LIST_USERS_REQUEST";
export const LIST_USERS_SUCCESS = "LIST_USERS_SUCCESS";
export const LIST_USERS_FAIL = "LIST_USERS_FAIL";

//STUDY

export const CREATE_STUDY_REQUEST = "CREATE_STUDY_REQUEST";
export const CREATE_STUDY_SUCCESS = "CREATE_STUDY_SUCCESS";
export const CREATE_STUDY_FAIL = "CREATE_STUDY_FAIL";

// LIST STUDY
export const FETCH_STUDY_REQUEST = "FETCH_STUDY_REQUEST";
export const FETCH_STUDY_SUCCESS = "FETCH_STUDY_SUCCESS";
export const FETCH_STUDY_FAIL = "CREATE_STUDY_FAIL";

//DELETE STUDY
export const DELETE_STUDY_REQUEST = "DELETE_STUDY_REQUEST";
export const DELETE_STUDY_SUCCESS = "DELETE_STUDY_SUCCESS";
export const DELETE_STUDY_FAIL = "DELETE_STUDY_FAIL";

//STUDY DETAILS
export const STUDY_DETAIL_REQUEST = "STUDY_DETAIL_REQUEST";
export const STUDY_DETAIL_SUCCESS = "STUDY_DETAIL_SUCCESS";
export const STUDY_DETAIL_FAIL = "STUDY_DETAIL_FAIL";

//UPDATE STUDY
export const STUDY_UPDATE_REQUEST = "STUDY_UPDATE_REQUEST";
export const STUDY_UPDATE_SUCCESS = "STUDY_UPDATE_SUCCESS";
export const STUDY_UPDATE_FAIL = "STUDY_UPDATE_FAIL";
